server:
  port: 8888
spring:
  application:
    name: msa-weather-eureka-client-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  prefix: /haotian
  routes: 
    city: 
      path: /city/**
      service-id: msa-weather-city-eureka
    weather:
      path: /weather/**
      service-id: msa-weather-data-eureka
      
