server:
  port: 8084
spring:
  application:
    name: msa-weather-report-eureka-feign-gateway-hystrix
  thymeleaf:
    cache: false
eureka: 
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka/
feign:
  client:
    config: 
      feignName: 
        connect-timeout: 20000
        read-timeout: 20000
  hystrix:
    enabled: true      